import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Cairo } from "next/font/google";
const cairo = Cairo({
  subsets: ["arabic", "latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body
        className={`min-h-screen bg-background font-sans antialiased ${cairo.className}`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
